<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuratSeeder extends Seeder
{
    public function run(): void
    {
        $surat = [
            'Al-Fatihah',
            'Al-Baqarah',
            'Ali Imran',
            'An-Nisa',
            'Al-Maidah',
            'Al-An\'am',
            'Al-A\'raf',
            'Al-Anfal',
            'At-Taubah',
            'Yunus',
            'Hud',
            'Yusuf',
            'Ar-Ra\'d',
            'Ibrahim',
            'Al-Hijr',
            'An-Nahl',
            'Al-Isra',
            'Al-Kahf',
            'Maryam',
            'Ta-Ha',
            'Al-Anbiya',
            'Al-Hajj',
            'Al-Mu\'minun',
            'An-Nur',
            'Al-Furqan',
            'Ash-Shu\'ara',
            'An-Naml',
            'Al-Qasas',
            'Al-Ankabut',
            'Ar-Rum',
            'Luqman',
            'As-Sajdah',
            'Al-Ahzab',
            'Saba',
            'Fatir',
            'Yasin',
            'As-Saffat',
            'Sad',
            'Az-Zumar',
            'Ghafir',
            'Fussilat',
            'Ash-Syura',
            'Az-Zukhruf',
            'Ad-Dukhan',
            'Al-Jasiyah',
            'Al-Ahqaf',
            'Muhammad',
            'Al-Fath',
            'Al-Hujurat',
            'Qaf',
            'Adh-zariyat',
            'At-Tur',
            'An-Najm',
            'Al-Qamar',
            'Ar-Rahman',
            'Al-Waqi\'ah',
            'Al-Hadid',
            'Al-Mujadilah',
            'Al-Hasyr',
            'Al-Mumtahanah',
            'As-Saff',
            'Al-Jumu\'ah',
            'Al-Munafiqun',
            'At-Tagabun',
            'At-Talaq',
            'At-Tahrim',
            'Al-Mulk',
            'Al-Qalam',
            'Al-Haqqah',
            'Al-Ma\'arij',
            'Nuh',
            'Al-Jinn',
            'Al-Muzzammil',
            'Al-Muddassir',
            'Al-Qiyamah',
            'Al-Insan',
            'Al-Mursalat',
            'An-Naba',
            'An-Nazi\'at',
            'Abasa',
            'At-Takwir',
            'Al-Infitar',
            'Al-Mutaffifin',
            'Al-Inshiqaq',
            'Al-Buruj',
            'At-Tariq',
            'Al-A\'la',
            'Al-Ghashiyah',
            'Al-Fajr',
            'Al-Balad',
            'Ash-Syams',
            'Al-Lail',
            'Ad-Duha',
            'Al-Insyirah',
            'At-Tin',
            'Al-`Alaq',
            'Al-Qadr',
            'Al-Bayyinah',
            'Az-Zalzalah',
            'Al-`Adiyat',
            'Al-Qari`ah',
            'At-Takatsur',
            'Al-`Asr',
            'Al-Humazah',
            'Al-Fil',
            'Quraisy',
            'Al-Ma`un',
            'Al-Kautsar',
            'Al-Kafirun',
            'An-Nasr',
            'Al-Lahab',
            'Al-Ikhlas',
            'Al-Falaq',
            'An-Nas',
        ];

        foreach ($surat as $nama) {
            DB::table('surat')->insert([
                'nama' => $nama,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
